### ISSUE TITLE
Credstash has a method to list all secrets

### ISSUE THREAD

**Issue by DavidTanner** [roylines/node-credstash#13] opened 2016-08-22 19:31 UTC
Credstash fetches a list of all secrets in DynamoDB and returns the names and versions of all credentials. 
https://github.com/fugue/credstash/blob/v1.11.0/credstash.py#L167

This would address #8 in the same way that credstash does, do a list then search for matching keys and get them afterwards.
https://github.com/fugue/credstash/blob/v1.11.0/credstash.py#L579

PR forthcoming

**Comment by toadkicker** [comment] 2016-08-22 22:31
#8 is a dupe of this then

**Closed as completed** 2017-01-06 20:29 UTC
Labels: enhancement
